### ISSUE TITLE
The use of `id`

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/KielMAT#103]
https://github.com/neurogeriatricskiel/KielMAT/blob/52a0386b1e4f2df6e8950db50abdf1f94aef5a7a/kielmat/datasets/keepcontrol.py#L112

Should we agree on avoiding the use of `id` as a variable? This variable name is too generic in my view. It does not make clear if we are talking about the subject id, the task id, the trial id, et cetera. 

I propose to explicitly use `sub_id` (or `subject_id`) so that it is clear. 

What do you think?

BR
Robbin

**Comment by JuliusWelzel** [comment]
Fixed in https://github.com/neurogeriatricskiel/KielMAT/commit/f71a1d4cbb10bf4b49a5e42b0d91f0208eecbef2. Now using `subject_id`
