### ISSUE TITLE
Consistency between docstring example and code

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/KielMAT#104]
https://github.com/neurogeriatricskiel/KielMAT/blob/52a0386b1e4f2df6e8950db50abdf1f94aef5a7a/kielmat/utils/kielmat_dataclass.py#L182

Should we agree on the use of lowecase/uppercase? In the docstring you write:

"""Add information to the info dictionary. Valid keys are : 'Subject', 'Session', 'Task'. [...]"""

But then you give a warning if people use "Task" and you convert it to "task". 

Do you want to update the docstring? Or get rid of the warning?

BR
Robbin

**Comment by JuliusWelzel** [comment]
Hi, @rmndrs89. I changed it as follows: https://github.com/neurogeriatricskiel/KielMAT/commit/f71a1d4cbb10bf4b49a5e42b0d91f0208eecbef2#diff-9f8d2e8398a7d1666f713304778b62f7667c1801d97765178c853825a48a25c9. Is that fine?
