### ISSUE TITLE
Postural transition detection

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/KielMAT#106]
https://github.com/neurogeriatricskiel/KielMAT/blob/f1ff9b7ea486363d8535ab32800914b1ebdda1fa/ngmt/modules/ptd/_pham.py#L265

We have to check if this is now the desired behavior. The idea is to find peaks in the tilt angle to find candidate transitions. However, if the sensor is orientated differently, it may be that these candidate peaks should be negative peaks.

Let us check this with some examples before pull request is fully approved and merged.

**Comment by rmndrs89** [comment]
- [ ] Apply orientation estimation with `vqf` to align the sensor data with the horizontal plane
- [ ]

**Comment by masoudabedinifar** [comment]
Dear @rmndrs89,

I applied VQF orientation estimation to the postural transition detection module and updated some parts of the code accordingly as we discussed with this commit: 7ce0b8e5fde50c0d6e13246d2e5b515d9a648475. Could you please check the alterations and, if it's as you mentioned, close the issue?

Thanks!

Best,
Masoud
