### ISSUE TITLE
Consistent sensor units usage in KielMAT

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/KielMAT#107]
https://github.com/neurogeriatricskiel/KielMAT/blob/e0fd30a8eb32e020d9dd3016c94a9861150e5d34/kielmat/modules/gsd/_paraschiv.py#L65

For me it is still not clear in what units the data needs to be provided. Should we design the algorithms such that they always get data in SI units, i.e.:

| Type | Units |
|------|-------|
| accel | m/s^2 |
| gyro | rad/s   |

Or should we always provide the information of the units to the call of the function?

**Comment by masoudabedinifar** [comment]
Dear @rmndrs89,

This issue is currently mentioned in [Orientation estimation using VQF](https://github.com/neurogeriatricskiel/KielMAT/issues/106) and will be handled altogether.

Best,
Masoud

**Comment by masoudabedinifar** [comment]
Dear Robbin,

I am updating all Modules, examples, and all related sections to be in the SI unit. I did all alterations for the GSD Module in this commit: 5e827cfe6026dc8ebcd7d5dba4508f9b0cf0a52e and I will apply similar alterations for all modules. 

Best,
Masoud

**Comment by masoudabedinifar** [comment]
Dear Robbin,

I made all the units consistent through all modules and their corresponding files with commits: 856b714cd6bb96afb40e1fb700efc9730ee3a496 , a2db32f87c0010b6a09fbb653981f036d81ab19c , 7374b850c3bb8b29e7223894087af6ee7abbdbed and 5e827cfe6026dc8ebcd7d5dba4508f9b0cf0a52e

Could you please check the changes and close the issue?
Thanks!

Best,
Masoud
