### ISSUE TITLE
Virtual environment

### ISSUE THREAD

**Issue by rmndrs89** [neurogeriatricskiel/KielMAT#13]
Hi @masoudabedinifar and @hansencl and @JuliusWelzel,

we still need to look at that cross-platform `conda` or `pip` environment file. I have just pulled the `main` branch to update the dataset definitions, and I get the following:

```
No module named 'pywt'
  File "/home/robbin/Projects/NGMT/ngmt/modules/gsd/GSDA.py", line 7, in <module>
    import pywt
  File "/home/robbin/Projects/NGMT/test.py", line 5, in <module>
    from ngmt.modules.gsd import GSDA
ModuleNotFoundError: No module named 'pywt'
```
Obviously, I can just intall `pip install PyWavelets` or `conda install pywavelets`, but it is also not clear from the `environment.yml` that this packages is required.

Best, 
Robbin

**Comment by rmndrs89** [comment]
I have looked a bit at `poetry`, see, e.g.:

- [https://www.freecodecamp.org/news/how-to-build-and-publish-python-packages-with-poetry/](https://www.freecodecamp.org/news/how-to-build-and-publish-python-packages-with-poetry/)
- [https://realpython.com/dependency-management-python-poetry/](https://realpython.com/dependency-management-python-poetry/)

Especially, the first source I found very useful, as it also includes writing some test functions. Could be something for @masoudabedinifar to checkout in a lightweight version of the `NGMT` package? For example, if we create a demo package that only performs the following steps:

1. resample to 40 Hz
2. compute the signal norm

With a few commands the package can then be build `poetry build` and published to PyPI `poetry publish`.

I am, however, still not sure how this works across Windows, MacOS and Linux operating systems.

**Comment by JuliusWelzel** [comment]
I was able to easily create an venv using poerty. @rmndrs89 could you, please try for Linux.

Just install poerty, clone the repo and `cd` to the clone. I updated the install instructions in https://github.com/neurogeriatricskiel/NGMT/commit/0486575b3d9b53d9d9ca5802b58239bd3f7d77dc

**Comment by rmndrs89** [comment]
Hi @JuliusWelzel,

apart from some typos in the installation guideline, I have managed to clone the repo and install the environment:

```bash
$ git clone https://github.com/neurogeriatricskiel/NGMT.git
$ cd NGMT
$ poetry install
```

However, when trying to run the [example for gait sequence detection](https://github.com/neurogeriatricskiel/NGMT/blob/main/examples/GSDB_example.ipynb) in VS Code, I encountered already two missing libraries, `ipykernel` and `matplotlib`.

Did you not include these libraries on purpose, or were they omitted when creating the poetry virtual environment?

**Comment by JuliusWelzel** [comment]
I added the required packages in 94134b0b42f79d5a91b159a4a9d128e49ea87fd3. 

Closing now 💯 
If you encounter new problems, please open a new issue!
