### ISSUE TITLE
Where to store subject and tracking system information?

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/KielMAT#88]
Motion-BIDS stores subject and tracking-system information in different `.json` files. We have in the `NGMTRecording` class currently only info implemented with three valid keys. Should we allow dictionaries from each tracking system where information about the device is stored?

**Comment by JuliusWelzel** [comment]
Implement this in the following way: 

1. Rename `info` attribute to `recording_info`  
2. combine information from filename (sub-, ses-, tracksys-) and `motion.json` in the `recording_info`

**Comment by rmndrs89** [comment]
Please note that we don't always have that info in the filename, for example, for the Mobilise-D and IDEA-FAST datasets, it works a bit differently (as this is data from the home assessment)

**Comment by JuliusWelzel** [comment]
Done in https://github.com/neurogeriatricskiel/KielMAT/commit/bcab3307bc1981068ed55ba774f4e5bf288f5df1
