### ISSUE TITLE
Most of the example files not available

### ISSUE THREAD

**Issue by davidpagnon** [neurogeriatricskiel/KielMAT#90]
Hi, 

The code is very well written and a pleasure to review, thanks for this effort!

However, most of the example files (at [Home](https://neurogeriatricskiel.github.io/NGMT/) and [examples](https://neurogeriatricskiel.github.io/NGMT/examples/) and in the [corresponding notebooks](https://github.com/neurogeriatricskiel/NGMT/tree/main/examples)) are not available. It would be nice to upload them to https://github.com/neurogeriatricskiel/NGMT/tree/main/examples/data so that the new user can try out the code.

Not available:
- Mobilise-D/rawdata/sub-3011/Free-living/data.mat for Home example
- examples/data/exMobiliseFreeLiving.mat for "Tutorial basics", "Events in dataclass", "Initial Contact Detection"
- sub_023\sub-023_imu-LARM_20160510_075144.csv for "Physical activity monitoring"
- sub-pp002\motion\sub-pp002_task-homePart1_tracksys-imu_motion.tsv for "Sit to stand and stand to sit detection"
- examples/data/exKeepControl.tsv for "modules_04_ssd.ipynb"

Minor remark: the content of the ipynb files is not totally equivalent to the examples and modules on the website.

**Comment by davidpagnon** [comment]
In "Installation and usage" (L85 of the JOSS paper), it may be worth adding a line stating that the example data were gathered in accordance with the Declaration of Helsinki https://joss.readthedocs.io/en/latest/policies.html#joss-policies

**Comment by rmndrs89** [comment]
This issue has been addressed by fetching datasets from Zenodo (Mobilise-D) and OpenNeuro (Keep Control)
