### ISSUE TITLE
Name changing to the Kiel Motion Analysis Toolbox (KielMAT)

### ISSUE THREAD

**Issue by masoudabedinifar** [neurogeriatricskiel/KielMAT#94]
Dear @rmndrs89 and @JuliusWelzel 

Based on our last discussion, I have changed all references to the "Kiel Motion Analysis Toolbox (KMAT)" in commits 32d62a3fe5792e3ccea451be69f2f8a1442defa0, 2a11cda3ac0e2ec15585a45c4931ae6f623cac42 and b151fe55f1ea58a06b5f265e8a0dc06cd75b2d1b in the rename_toolbox. I also applied all the revisions needed for the paper and documentation of the toolbox in the same branch.

I would appreciate it if you could review the changes and provide any necessary feedback. Additionally, the following files also need to be updated with the new name:

- [x] [https://github.com/neurogeriatricskiel/KielMAT/blob/main/paper/ngmt_flow.png](https://github.com/neurogeriatricskiel/KielMAT/blob/main/paper/ngmt_flow.png)
- [x] https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/ngmt_logo_transBG.png
- [x] https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/ngmt_logo_whiteBG.png
- [x] https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/docs/ngmt_logo_transBG.png
- [x] https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/info/Transition%20Algorithms%20to%20Python.pptx

Best wishes.
Masoud

**Comment by rmndrs89** [comment]
Hi all,

Walter suggest to change the name to `kielmat` rather than `kmat`, since having **Kiel** explicitly in the name provokes to make direct associations, and thus it'd be easier to memorize.

Is this still possible, @masoudabedinifar and @JuliusWelzel ?

Best regards,
Robbin

**Comment by masoudabedinifar** [comment]
Hi @rmndrs89 

Sure, I will revert the changes and use `kielmat` instead `kmat`.

Best,
Masoud

**Comment by JuliusWelzel** [comment]
Can you rename it to KielMAT at all instances?

**Comment by masoudabedinifar** [comment]
I renamed as:

- `Kiel Motion Analysis Toolbox` instead of `NeuroGeriatrics Motion Toolbox`
- `kielmat` instead of `ngmt`
- `KielMAT` instead of `NGMT`

with this commits:  0fd4bc513aa963b72a4b111ad07d4953a4073875 and a01523a0c73f681a954d83c76958f392faada036

**Comment by JuliusWelzel** [comment]
I have to say, reading KielMATrecording seems a little more chunky than KMATrecording. What do you think?

**Comment by JuliusWelzel** [comment]
> * [ ]  https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/paper/ngmt_flow.png
> * [ ]  https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/ngmt_logo_transBG.png
> * [ ]  https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/ngmt_logo_whiteBG.png
> * [ ]  https://github.com/neurogeriatricskiel/NGMT/blob/rename_toolbox/docs/ngmt_logo_transBG.png

The files names for the logos will be changed with the new logo

**Comment by masoudabedinifar** [comment]
[https://github.com/neurogeriatricskiel/KielMAT/blob/main/paper/ngmt_flow.png] file was deleted with commit: 4e230eae5ad67b8b1bd9e7d995e9bacb1cc91f55 ,

**Comment by masoudabedinifar** [comment]
all files were removed.
